aws_profile                = "devops_demo"
aws_region                 = "us-east-1"
vpc_cidr_block             = "10.0.0.0/16"
public_subnet_count        = 2
private_subnet_count       = 2
public_subnet_cidr         = ["10.0.1.0/24", "10.0.3.0/24"]
private_subnet_cidr        = ["10.0.2.0/24", "10.0.4.0/24"]
eip_count                  = 2
db_rds_dbname              = "testdb"
db_rds_username            = "testuser"
db_rds_password            = "testpass123"
enable_rds_secret_rotation = true
